# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build YaSolR Pro

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 5 * * 1"
  # push:
  #   tags: ["v*"]
  #   branches: ["*"]
  #   paths-ignore: ["docs/**", "**/*.md", "**/portal/**", "tools/**", "test/**"]
  # pull_request:
  #   paths-ignore: ["docs/**", "**/*.md", "**/portal/**", "tools/**", "test/**"]

# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true

jobs:
  pio_envs:
    if: ${{ github.repository == 'mathieucarbou/YaSolR' }}
    name: Get PlatformIO Envs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pio_envs
          path: ~/.cache/pip

      - name: Pyhton
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Get Envs
        id: envs
        run: |
          rm -f platformio_override.ini
          echo "pio_name=$(pio project config --json-output | jq -cr '.[0][1][0][1]')" >> $GITHUB_OUTPUT
          # echo "pio_default_envs=$(pio project config --json-output | jq -cr '[ .[][0] | select(startswith("env:pro-")) | select(contains("-debug")|not) | .[4:] ]')" >> $GITHUB_OUTPUT
          echo "pio_default_envs=$(pio project config --json-output | jq -cr '[ .[][0] | select(startswith("env:pro-") or startswith("env:trial-")) | select(contains("-debug")|not) | .[4:] ]')" >> $GITHUB_OUTPUT
          # echo "pio_default_envs=$(pio project config --json-output | jq -cr '[ .[][0] | select(startswith("env:pro-") or startswith("env:trial-") or startswith("env:oss-")) | select(contains("-debug")|not) | .[4:] ]')" >> $GITHUB_OUTPUT

    outputs:
      pio_name: ${{ steps.envs.outputs.pio_name }}
      pio_default_envs: ${{ steps.envs.outputs.pio_default_envs }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [pio_envs]
    strategy:
      matrix:
        environment: ${{ fromJSON(needs.pio_envs.outputs.pio_default_envs) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Tags
        run: git fetch --force --tags origin

      - name: Remove Pro Content
        if: ${{ startsWith(matrix.environment, 'oss-') }}
        run: |
          rm -f -r -v \
            lib/ElegantOTAPro \
            lib/ESPDASHPro \
            lib/WebSerialPro

      - name: Remove OSS Content
        if: ${{ startsWith(matrix.environment, 'pro-') }}
        run: |
          rm -f -r -v \
            lib/ESPDASH

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pio
          path: |
            ~/.cache/pip
            ~/.platformio

      - name: Cache PlatformIO Dependencies (OSS)
        if: ${{ startsWith(matrix.environment, 'oss-') }}
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pio-oss-${{ matrix.environment }}
          path: .pio

      - name: Cache PlatformIO Dependencies (Pro)
        if: ${{ startsWith(matrix.environment, 'pro-') }}
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pio-pro-${{ matrix.environment }}
          path: .pio

      - name: Cache PlatformIO Dependencies (Trial)
        if: ${{ startsWith(matrix.environment, 'trial-') }}
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pio-trial-${{ matrix.environment }}
          path: .pio

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          ref="${{ github.ref_name }}"
          ref="${ref//\//}"
          ref="${ref//-/}"
          ref="${ref//_/}"
          # lang: en
          pio run -e ${{ matrix.environment }}
          mv .pio/build/${{ matrix.environment }}/firmware.bin ./${{ needs.pio_envs.outputs.pio_name }}-$ref-${{ matrix.environment }}-en.OTA.bin
          mv .pio/build/${{ matrix.environment }}/firmware.factory.bin ./${{ needs.pio_envs.outputs.pio_name }}-$ref-${{ matrix.environment }}-en.FACTORY.bin
          mv .pio/build/${{ matrix.environment }}/firmware.elf ./${{ needs.pio_envs.outputs.pio_name }}-$ref-${{ matrix.environment }}-en.elf
          # lang: fr
          sed -i 's/YASOLR_LANG_EN/YASOLR_LANG_FR/' platformio.ini
          pio run -e ${{ matrix.environment }}
          mv .pio/build/${{ matrix.environment }}/firmware.bin ./${{ needs.pio_envs.outputs.pio_name }}-$ref-${{ matrix.environment }}-fr.OTA.bin
          mv .pio/build/${{ matrix.environment }}/firmware.factory.bin ./${{ needs.pio_envs.outputs.pio_name }}-$ref-${{ matrix.environment }}-fr.FACTORY.bin
          mv .pio/build/${{ matrix.environment }}/firmware.elf ./${{ needs.pio_envs.outputs.pio_name }}-$ref-${{ matrix.environment }}-fr.elf

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.environment }}
          if-no-files-found: error
          path: |
            *.bin
            *.elf

  release:
    name: Release
    if: ${{ github.repository_owner == 'mathieucarbou' && github.event_name != 'pull_request' && ( github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') ) }}
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Move
        run: |
          ls -R artifacts
          find artifacts -name '*.bin' -exec mv {} artifacts/ \;
          find artifacts -name '*.elf' -exec mv {} artifacts/ \;

      - name: Pre-Release
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: mathieucarbou/marvinpinto-action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.ACCESS_TOKEN }}"
          automatic_release_tag: latest
          prerelease: true
          title: Pre-release Builds
          files: |
            artifacts/*.bin
            artifacts/*.elf

      - name: Changelog
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          failOnError: true
          commitMode: true
          configuration: ".github/workflows/release-notes-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: softprops/action-gh-release@v2
        with:
          body: ${{steps.github_release.outputs.changelog}}
          draft: false
          files: |
            artifacts/*.bin
            artifacts/*.elf
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
